name: Clojure CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      uses: DeLaGuardo/setup-clojure@master
      run: clojure -M:test

    - name: Antq Action
      uses: liquidz/antq-action@v1.3
