name: Clojure CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - uses: DeLaGuardo/setup-clojure@master
      with:
        cli: 1.11.1.1113
    - name: Run tests
      run: clojure -M:test

  antq:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - name: antq
      uses: liquidz/antq-action@v1.3
